server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: pepeti
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDR+d4U19mBBlZ+
    AYDOUUFC1WlxCFx9cn7MzsC/RVaV3G12VubG76Ov5y3x+4U6riulfZU4hXw1X0/8
    QUTwV1ouCbeH1CWTM/j0f+1xOh5d/GxN2WwtwI8+9jY8/3ZbdlX9+tI4tmWZi6ON
    3DWzcs++Zw/WfD9culABiJ+PtGXKZnGC7c+dyg6RKjHAJheZlVH31lylBmlCnI8h
    1hOS2R1jcPEl/3+4rqq3FjUQ7dgrUGos9d9DKXER0tkSR0Nv30SudhJoNe/noBIt
    y+WWdF7MYsQMcrxMroAgn5YTLAUsZDSot8OHxFAjG8WyP7HMrNhq5Dfmj5NDh8pc
    DEaCZc3rAgMBAAECggEAV/reNtWKaSmCrCFtGwWo1pwdJiNevaFvx9kJohsngHtv
    0hnvcIOQjm/LLI068a9w0lKgZ6JmvOZG2Wdvv1SakJe5sswNQnSQZ8ICd2LmvnK5
    3pSvYyw/2R3I9B4GNaSLu3ORCfpC7+c2jIYsahg9O4ZreG9vDSdzxnC8irYHwJoR
    D2b2Bpb/cs1O9JoR1D9dXTdkCzh6wI7PXnZCVsN7ZeuFc6eBGcPZP2aRYh8GwRVm
    7nCk89gzVWxbMza86aADOKkcmRSLWKMGiq/6vjlP7KUDqG03oKS5SZQ9kir2l49q
    oTV1+mrhaUYEXgXd2Dq6AT/rpWtwuTQ94CGIhfMGwQKBgQD8Z/H+b6bIDlfBUMZK
    FJocCC7EDFyYBjwRV9NhUXS86tuUyBnwxxvMKYIlpfVOxcjekty0LLYW2dK0U5aH
    HCqwDLYTkXSWqizXr8lhsvyxrcYZ10rG+0EOFiVKdF3TFJXMWrYiYW84FrnZgSd+
    9J/f+q7RMjwbqDztqM1JchL42QKBgQDU90JSATr5J03HtuzjRouyXpZRm6RHqUA8
    VQ1REQvnQ3RTwqWinwpupqOtfH5dUW2qXkA3nN9aigrztjUULiUnLXmKsgz4T40d
    po75vlzhrlvGwkFtYGC2HLLV+7qJVFj1eyoY7aSGRyhnvDR3U8aLgz8DiUOPukWc
    2u3DdGDiYwKBgCwtyXaedlPH5uZITBzFVGAZso3QGBjn5nWmqLH8/vDeLsbw61Fw
    mFX44fXTAYfjKJCEpirHNKv1PmMfylYlwPcFko0ERaLlcGnkM9xs5rv2zZjSTR1c
    9vsPN0G78nwyuzGEoyKLaVso5yjB6XbYPG+IwjaNk2XH4bo7dIspc1apAoGBALYL
    3x9medj95hkwn3LwnP4OqQR9vYKchZKNSeLgZYJ9QPVQ0HIg7bQEsqncX9C5iLs3
    8kEX0j38/ruyJ9FmWNASqXEMHtYsen68IEAQoCky+LUA3Rj4Z/OEuML+ekhmV90Q
    Ob4xdpBqR3nVgiv26yPbP4RwU9aK7nLVGqYX17HtAoGBAOQm4MELp1KJWJzkEqG4
    t8bdT0Gh0TAZRTf7w0+xIccKGs5CG/9kZh649ME5YMFFXrrUCg1ttMs/9iGembKh
    +bb8uigUbSYb6HXXu7+MepxKK5qLEDihUzy6nyfFR/VHjBzUkNEZSlx25ipoIfqc
    9nV/sCr45y5WpkdoB2U2vK7K
    -----END PRIVATE KEY-----

  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0fneFNfZgQZWfgGAzlFB
    QtVpcQhcfXJ+zM7Av0VWldxtdlbmxu+jr+ct8fuFOq4rpX2VOIV8NV9P/EFE8Fda
    Lgm3h9QlkzP49H/tcToeXfxsTdlsLcCPPvY2PP92W3ZV/frSOLZlmYujjdw1s3LP
    vmcP1nw/XLpQAYifj7RlymZxgu3PncoOkSoxwCYXmZVR99ZcpQZpQpyPIdYTktkd
    Y3DxJf9/uK6qtxY1EO3YK1BqLPXfQylxEdLZEkdDb99ErnYSaDXv56ASLcvllnRe
    zGLEDHK8TK6AIJ+WEywFLGQ0qLfDh8RQIxvFsj+xzKzYauQ35o+TQ4fKXAxGgmXN
    6wIDAQAB
    -----END PUBLIC KEY-----

  access-token-expiration: 900000
  refresh-token-expiration: 604800000
