server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: pepeti
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAlFEw82wdTHv72WR5RNyxXzixbN7eoLDcu4OFH+LbBIZjSwuq
    VpaYgiIo0jMOWE5qzbiGqt7h13O4FLfIeGYr0AzgEv8agcx7fQTT98YU5ZBz4RL0
    3gguP/tlHiDvuVQyJdO3cVeAljXqOr/MvnsbKAREAX9AQGYf9sXJi0IxX5lam5v5
    9S0OT4+mcxXvcbH3U5LHDZZmO4++YMgZOAX9reTSs6P1BDYAlRfIgpRWpuZ7PLXX
    LociNbcsWVtP9vkPMF9aslu380r/x3i3BplzMjSnkR05PdKfgvhD33X646WQ1mY9
    5+uC4WIeQqnon/594lXstof9I4fshNwjzTs0ewIDAQABAoIBAFlolFy5mPPpbcoA
    Ioabj6U6VOKve39c/sNfJloxdBxHMwYjUxz9jZQtKXSFaKldJE89ZJkO4Q/zZ029
    +HB0DwdNK6rn87+5V9vmlC0yUJiOuvw8ZDaQsejKEIvYCQsssUpSVaxStmZWvAuM
    Yc2WAqnd4G0Sm9X2emBVnQiA76iTqOqmuMS6+8wTPEYOnA58M1ySKwrZdWcznglK
    F00MukvZYqCq664aK7zQFMbq+4LL/JtHdKh98dX8+xvV0HlvUnun3blk09vAXMB4
    RFRMW4d5IxGO+w4Zd2p++pjY40+VcLQpNnyfkHRy/dAIfuJSe5g1dHGcgqABaRFe
    XM4D3lECgYEA4140NMGS/Eg7zr1UAKTS19XJ34urOIfcMD0TksjSPEuni/meeQQt
    l0lp7kEMF2iBzWhaEMpBP2XISjAz9JhQOOMqU2AtCeM4556ts7j5ZnaWO0cTjEcK
    oNS0gDeWAL2ih5zo5lnROz6TjuBPPGz5+nOjLkN9oWklGdva100MQJMCgYEApv6U
    NN27dteLdqi/Kkjp+KcLjV9aERofOsbQxFyNjRZmrfT/YnMrBXQ346iErII1U/pe
    dUH1TN5db48fEtob1fb72rLxTQ/a/IEes5+Gtu8hI0aspzjpTfL7KcyKk/bl/CTx
    SDLpRAAsHwRHC7G49xfwYfY7anQV86g2NK9M9XkCgYBHjtR7bhjmkY1RKcEQWs+I
    4l4gnwKKTif8fpx0bAPOujjHEw7PI4N9w7s1Iv+9NkTz8s21zxHt9AivYLBZYL6O
    yN//UZubKwozy3r7v1Gu78+kZGBAm/M6XvdYCyaIoSZP7BBYvxfcv3sNUoddiya5
    rj9DRjZ54G+uzcT4UeVzRQKBgGDiNg3tzoMGTm1LPY1EvCl8kKE2fsSJSTEKg7hI
    kf8Wzf+Csl/lvUHuyTYVYNPMvy+3g/G3kJ9GKyM7/6UqURfzsO6S/pfc6Qmxx6Qi
    mz+qwKj8qdJinEiS/dCkUInDpm6A6FMg5mCDURW1n5pTQ6JnixjqiFIcg1fXcYtj
    YNzRAoGBAIXH9uG5YhJSAjottFku94TGjxI+WjMwt0Lgn/suFB3iBTdviXqytrYw
    ELC0/U053f9+bun4VOE8UJTXpWlQCLl/j7RFNErJKevlTEPauZ5oUHD2CLV/M5+X
    zb8NoccTV0NFK3wBegLiZHE6HkyozFbzL/yRR1R58YQuwMANd5Ew
    -----END RSA PRIVATE KEY-----

  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlFEw82wdTHv72WR5RNyx
    XzixbN7eoLDcu4OFH+LbBIZjSwuqVpaYgiIo0jMOWE5qzbiGqt7h13O4FLfIeGYr
    0AzgEv8agcx7fQTT98YU5ZBz4RL03gguP/tlHiDvuVQyJdO3cVeAljXqOr/Mvnsb
    KAREAX9AQGYf9sXJi0IxX5lam5v59S0OT4+mcxXvcbH3U5LHDZZmO4++YMgZOAX9
    reTSs6P1BDYAlRfIgpRWpuZ7PLXXLociNbcsWVtP9vkPMF9aslu380r/x3i3Bplz
    MjSnkR05PdKfgvhD33X646WQ1mY95+uC4WIeQqnon/594lXstof9I4fshNwjzTs0
    ewIDAQAB
    -----END PUBLIC KEY-----

  access-token-expiration: 900000
  refresh-token-expiration: 604800000
