server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: pepeti
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEowIBAAKCAQEAwEkL59P95955DoG3I/qc+haEcorwyBQBROeWB+TGAYstKreHFNeI+q3dWH1mxxqG0sdYfln7aSTmGbGf8Vf3zJWJnProzmun6vAmEBuBkoqxjj/dLFyXYgQzvMpT62VVZ/mb7pArFfPehWYsRrTwvLILo8uPnLXdiwkmRXkDm8q9OI7rbOI6XjrLXBLiQIIY2gd7wFyNubgFinJv2QB/l1ZoHyX5rSxvr5natBlNcz3eXL3zDYfYkfCiyAnrBXvsUSsWe/gxQmsjqdw7pp4AU+gkWxJkeKfXtNraFtsd8zMpECOKrKzhR6j6XzkuGEaYO+2HySY0HNY4DWR9/36JWwIDAQABAoIBAEE8x0BJSVzQuyuz0MnxLi8fUqJ2B0kqmF+jXuCgupkteg6DI95rXfsG4BE0wpkMo++BWMHNj6HVtgfDnutIGDeeCIltC211Uww/m/pdCrIIQkNr4YM6itXjbRZBYwV7ZOWY51GiMiwJiFakGqOGoiKzGYXh+4CEp3yThxuM+i9xm/JDVxmwSlLTCEdvS7oq4LuQFXc3rFEm3ocLtBN9zSMQKTZujpAd9f1p4oDdomo2rgs10A5ns92dNimLNXtLK9MXoYpajcXZ42SBuE+Gx3rttFJsSh9A3WWZGnJ/WfU2Si7KX28CfgkhMWoExTpeRPK3jupXyG6kdGVrm0+JfZECgYEA5GcszRCKXlU30aM3xDddvkDLmH2Yrn6U7SKMts9ccAV9ZK+86JXbMeJKHm/AdxupP5/H5HNO47BBVvrAcb1E7SYNULIqhZgpAs/zkPaky10NF2XKX3482jfvGYi7/pBE0/D2vb1GF+d/xpGnAw+3IWUZT2ib6iZejISKFlWOi5MCgYEA14SzbAGxoRLotlclko6qzuy4NXlwyQkEZ4PoILC8Z4Wg6sRHN60ZsxuF9uJslFljFif6zCf9UGu6sml2M/RJSkdXhDVQcxhdWssiydQIRx/Of4a7/MkyyTBZ5nBTx5FCCq/Vj6Iun7OYhNrSHE5lFG85y6VY/cA0ydPlttQCeBkCgYBmfy6Jr9yITLHJ7/b8pOP6ltVGz0YPOFrYt+Jxv0h6NNx6rKqXrXg6QJSGaBv014LyPF/V0zEZ2GTaBZkK8abWzXa4Odv/K7NrwapJ6YU2hcF0OIfCpsHkI6m2ybejm1ZnzgDMUP39iDO9BmvuYcUKxXXAPu+I+kL/yBK3xxk65QKBgHLKqLJ/mHgd1TvB4S5VtR7wMRGydGNv3Ruxw4Md/8v3/gTttK0wEv82Sr18Tq8ZiVB0zP3O0vrx1ohO6fm0RRE+PJwbtZUIRjkk94ue1yXjCB8eyaRUGivVCB1YeRdUBGQi0dJmZQUFKNiioMUY8HfY4mTY1jSaGsPhjHo8JHCJAoGBAIJcwbp7u+lA6LFtutBNw5Kk6OiwS7d9a/Yq/BIQB3bE+39tKyonq6G8uFL1eqhtkZly5czJv18V9rmfz9vTjntA6cX6+5hAveutg5977dF9BvL/S69/MOdReU1D8lpFW6Ab+c9lIAd6EKT+GTeASzkB032v1etRWfb07TRcmh7W
    -----END PRIVATE KEY-----

  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwEkL59P95955DoG3I/qc+haEcorwyBQBROeWB+TGAYstKreHFNeI+q3dWH1mxxqG0sdYfln7aSTmGbGf8Vf3zJWJnProzmun6vAmEBuBkoqxjj/dLFyXYgQzvMpT62VVZ/mb7pArFfPehWYsRrTwvLILo8uPnLXdiwkmRXkDm8q9OI7rbOI6XjrLXBLiQIIY2gd7wFyNubgFinJv2QB/l1ZoHyX5rSxvr5natBlNcz3eXL3zDYfYkfCiyAnrBXvsUSsWe/gxQmsjqdw7pp4AU+gkWxJkeKfXtNraFtsd8zMpECOKrKzhR6j6XzkuGEaYO+2HySY0HNY4DWR9/36JWwIDAQAB
    -----END PUBLIC KEY-----

  access-token-expiration: 900000
  refresh-token-expiration: 604800000
